### ISSUE TITLE
webuntis-api

### ISSUE THREAD

**Issue by zhgrui** [TotallyInformatik/annette-entwickelt-software-api#1]
Eine Schnittstelle für die Informationen des automatischen Stundenplans. Die "stundenplan.ts" Datei unter pages/api/annette-app ist hierfür der Einstiegspunkt.

**Comment by 123654-dev** [comment]
Die Stundenplan-API funktioniert nun und kann mit [domain/api/annette_app/dateien/stundenplan/[klassenname] verwendet werden. Zurück erhält man im Prinzip einen Ausschnitt der großen Textdatei für die ausgewählte Klasse, der beim Request aus den erhaltenen Daten erzeugt wird.
